#!/bin/bash

# case 1: str >> SimulationTime; break;
# case 2: str >> h; break;
# case 3: str >> Nneur; break;
# case 4: str >> W_P_NUM_BUND; break;
# case 5: str >> BUND_SZ; break;
# case 6: str >> f_name; break;
# case 7: str >> seed; break;
# case 8: str >> rate; break;
# case 9: str >> w_p_start; break;
# case 10: str >> w_p_stop; break;
# case 11: str >> w_n; break;
# case 12: str >> par_f_name; break;

# sim_time=2000
# Nneur=100
# h=0.1
# rate=180.0
# w_n=1.3
# w_p1=2.00
# w_p2=2.15
# w_p_nbund=15
# seed_nbund=1
# seed=0
# Ie=5.2

# params for 2 neurs
Nneur=2
sim_time=100000.
h=0.1
rate=185.0
w_n=5.4
w_p1=1.4
w_p2=4.4
w_p_nbund=30
seed_nbund=5
seed=0
Ie=5.4

par_fname=nn_params_$Nneur.csv
let "Ntotal = Nneur*w_p_nbund*seed_nbund"
echo "Total Neur Num: $Ntotal"
fname=N\_$Nneur\_rate\_$rate\_w_n_$w_n\_Ie\_$Ie
mkdir $fname
for j in `seq $seed $[$seed_nbund + $seed - 1]`;do
    mkdir $fname/seed\_$j
done
head=`git log -1 --format="%h"`
r_str="./hh-cuda-$head $sim_time $h $Ntotal $w_p_nbund $Nneur $fname $seed $rate $w_p1 $w_p2 $w_n $par_fname $Ie" 
echo $r_str > $fname/params
$r_str 2> $fname/times
# $r_str 1> $seed"_oscill.csv"
