#!/bin/bash

# case 1: str >> SimulationTime; break;
# case 2: str >> h; break;
# case 3: str >> Nneur; break;
# case 4: str >> W_P_NUM_BUND; break;
# case 5: str >> BUND_SZ; break;
# case 6: str >> f_name; break;
# case 7: str >> seed; break;
# case 8: str >> rate; break;
# case 9: str >> w_p_start; break;
# case 10: str >> w_p_stop; break;
# case 11: str >> w_n; break;

sim_time=10000.
h=0.1
rate=180
w_n=1.3
# w_p1=1.92
# w_p2=2.07
w_p1=2.00
w_p2=2.15
# w_p1=2.14
# w_p2=3.19

Nneur=10
w_p_nbund=15
seed_nbund=10

par_fname=nn_params_$Nneur.csv
let "Ntotal = Nneur*w_p_nbund*seed_nbund"
for seed in `seq 0 0`; do
    fname=$rate\_$h\_seed_$seed\_w_n_$w_n
    echo "Total Neur Num: $Ntotal"
    mkdir $fname
    for j in `seq 0 $[$seed_nbund - 1]`;do
        mkdir $fname/$j
    done

    r_str="./hodgkin-huxley-cuda-neuronet $sim_time $h $Ntotal $w_p_nbund $Nneur $fname $seed $rate $w_p1 $w_p2 $w_n $par_fname"
    echo $r_str > $fname/params
    optirun $r_str 2> $fname/times

done
